repositories:
# Stable repo of official helm charts
- name: "stable"
  url: "https://charts.helm.sh/stable"

releases:
- name: "activemq"
  namespace: "watchn"
  chart: ./activemq/chart
  wait: true

- name: "catalog"
  namespace: "watchn"
  chart: ../../src/catalog/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "carts"
  namespace: "watchn"
  chart: ../../src/cart/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "orders"
  namespace: "watchn"
  chart: ../../src/orders/chart
  wait: true
  values:
    - components.yaml.gotmpl
    - messaging:
        activemq: 
          brokerUrl: "tcp://activemq-0.activemq:61616"

- name: "checkout"
  namespace: "watchn"
  chart: ../../src/checkout/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "assets"
  namespace: "watchn"
  chart: ../../src/assets/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "ui"
  namespace: "watchn"
  chart: ../../src/ui/chart
  wait: true
  timeout: 600
  values:
    - components.yaml.gotmpl
    - ingress.yaml.gotmpl